# Generated by Django 4.0 on 2021-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('explanation', models.CharField(max_length=512)),
                ('char', models.CharField(max_length=512)),
                ('pinyin', models.CharField(max_length=512)),
                ('lang', models.CharField(max_length=512)),
                ('lit', models.CharField(max_length=512)),
                ('structure', models.CharField(max_length=512)),
            ],
        ),
    ]
