# Generated by Django 4.0 on 2021-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=models.EmailField(max_length=64, unique=True), max_length=64, unique=True),
        ),
    ]
