# Generated by Django 4.0 on 2021-12-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.lang'),
        ),
    ]
