# Generated by Django 4.0.1 on 2022-01-09 13:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import structure.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('1', 'word_image'), ('2', 'word_char_from_lang'), ('3', 'word_lang_from_char'), ('4', 'word_char_from_video'), ('5', 'word_match'), ('6', 'sent_image'), ('7', 'sent_char_from_lang'), ('8', 'sent_lang_from_char'), ('9', 'sent_lang_from_video'), ('10', 'sent_say_from_char'), ('11', 'sent_say_from_video'), ('12', 'sent_paste_from_char'), ('13', 'sent_choose_from_char'), ('14', 'sent_delete_from_char'), ('15', 'dialog_A_char_from_char'), ('16', 'dialog_B_char_from_video'), ('17', 'dialog_A_puzzle_char_from_char'), ('18', 'dialog_B_puzzle_char_from_char'), ('19', 'puzzle_char_from_lang'), ('20', 'puzzle_lang_from_char'), ('21', 'puzzle_char_from_video'), ('22', 'draw_character')], max_length=2)),
                ('words_active_or_to_del', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('words_to_display', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('words_wrong', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('grammars_wrong', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('sent_char_A', models.CharField(max_length=120)),
                ('sent_pinyin_A', models.CharField(max_length=120)),
                ('sent_lang_A', models.CharField(max_length=120)),
                ('sent_lit_A', models.CharField(max_length=120)),
                ('sent_char_B', models.CharField(max_length=120)),
                ('sent_pinyin_B', models.CharField(max_length=120)),
                ('sent_lang_B', models.CharField(max_length=120)),
                ('sent_lit_B', models.CharField(max_length=120)),
                ('sent_char_W', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('sent_pinyin_W', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('sent_lang_W', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('media', models.JSONField(default=structure.models.default_task_media)),
                ('video', models.FileField(upload_to='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.character')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.grammar')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.lesson')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.word')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.topic'),
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.lang'),
        ),
    ]
