# Generated by Django 4.0.2 on 2022-02-24 18:21

import django.contrib.postgres.fields
from django.db import migrations, models
import structure.models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grammars_wrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=structure.models.default_1d_array, null=True, size=None),
        ),
    ]
