# Generated by Django 4.0 on 2022-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='topics'),
        ),
    ]
