# Generated by Django 4.0 on 2022-01-31 09:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import structure.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
        ('structure', '0003_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.character'),
        ),
        migrations.AlterField(
            model_name='task',
            name='grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.grammar'),
        ),
        migrations.AlterField(
            model_name='task',
            name='grammars_wrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        # migrations.AlterField(
        #     model_name='task',
        #     name='media',
        #     field=models.JSONField(default=structure.models.Task.default_media, null=True),
        # ),
        migrations.AlterField(
            model_name='task',
            name='sent_char_A',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_char_B',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_char_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_lang_A',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_lang_B',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_lang_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_lit_A',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_lit_B',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_pinyin_A',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_pinyin_B',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_pinyin_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.FileField(null=True, upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='task',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.word'),
        ),
        migrations.AlterField(
            model_name='task',
            name='words_active_or_to_del',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='words_to_display',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='words_wrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
