# Generated by Django 4.0 on 2022-01-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_task_character_alter_task_grammar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/topics'),
        ),
    ]
