# Generated by Django 4.0 on 2022-01-31 14:25

from django.db import migrations, models
import structure.models


class Migration(migrations.Migration):

    replaces = [('structure', '0007_alter_topic_image'), ('structure', '0008_alter_topic_image')]

    dependencies = [
        ('structure', '0006_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=structure.models.PathAndRename('images/topics/')),
        ),
    ]
