# Generated by Django 4.0 on 2022-01-31 14:40

from django.db import migrations, models
import structure.models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_topic_image_squashed_0008_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='media',
            field=models.JSONField(default=structure.models.default_task_media, null=True),
        ),
    ]
