# Generated by Django 4.0.2 on 2022-02-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.lesson'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('1', 'word_image'), ('2', 'word_char_from_lang'), ('3', 'word_lang_from_char'), ('4', 'word_char_from_video'), ('5', 'word_match'), ('6', 'sent_image'), ('7', 'sent_char_from_lang'), ('8', 'sent_lang_from_char'), ('9', 'sent_lang_from_video'), ('10', 'sent_say_from_char'), ('11', 'sent_say_from_video'), ('12', 'sent_paste_from_char'), ('13', 'sent_choose_from_char'), ('14', 'sent_delete_from_char'), ('15', 'dialog_A_char_from_char'), ('16', 'dialog_B_char_from_video'), ('17', 'dialog_A_puzzle_char_from_char'), ('18', 'dialog_B_puzzle_char_from_char'), ('19', 'puzzle_char_from_lang'), ('20', 'puzzle_lang_from_char'), ('21', 'puzzle_char_from_video'), ('22', 'word_write_from_video'), ('23', 'grammar_choose_from_video'), ('24', 'draw_character')], max_length=2),
        ),
    ]
