# Generated by Django 4.0.2 on 2022-02-14 14:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_alter_word_audio_alter_word_image_alter_word_video'),
        ('structure', '0011_alter_task_lesson_alter_task_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='words_active_or_to_del',
        ),
        migrations.RemoveField(
            model_name='task',
            name='words_to_display',
        ),
        migrations.AddField(
            model_name='task',
            name='grammars',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='task',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.grammar'),
        ),
        migrations.AlterField(
            model_name='task',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elements.word'),
        ),
    ]
