# Generated by Django 4.0.2 on 2022-02-14 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_remove_task_words_active_or_to_del_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='grammars',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None), default=[[]], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='grammars_wrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_char_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_lang_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_pinyin_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None), default=[[]], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='words_wrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], null=True, size=None),
        ),
    ]
