# Generated by Django 4.0.2 on 2022-02-14 14:52

import django.contrib.postgres.fields
from django.db import migrations, models
import structure.models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_alter_task_grammars_alter_task_grammars_wrong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='grammars',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None), default=structure.models.default_2d_array, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='grammars_wrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=structure.models.default_1d_array, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_char_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=structure.models.default_1d_array, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_lang_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=structure.models.default_1d_array, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='sent_pinyin_W',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=structure.models.default_1d_array, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None), default=structure.models.default_2d_array, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='words_wrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=structure.models.default_1d_array, null=True, size=None),
        ),
    ]
