# Generated by Django 4.0 on 2021-12-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_topic_lesson_lang_course_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='language',
            new_name='lang',
        ),
    ]
