# Generated by Django 4.0.2 on 2022-02-20 19:40

import django.core.validators
from django.db import migrations, models
import elements.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=64)),
                ('pinyin', models.CharField(max_length=64)),
                ('lang', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('audio', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('explanation', models.CharField(max_length=512)),
                ('char', models.CharField(max_length=512)),
                ('pinyin', models.CharField(max_length=512)),
                ('lang', models.CharField(max_length=512)),
                ('lit', models.CharField(max_length=512)),
                ('structure', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=64)),
                ('pinyin', models.CharField(max_length=64)),
                ('lang', models.CharField(max_length=64)),
                ('lit', models.CharField(max_length=64)),
                ('image', models.FileField(blank=True, null=True, upload_to=elements.models.PathAndRename('images/words/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])])),
                ('audio', models.FileField(blank=True, null=True, upload_to=elements.models.PathAndRename('audio/words/'), validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('video', models.FileField(blank=True, null=True, upload_to=elements.models.PathAndRename('video/words'), validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
            ],
        ),
    ]
