# Generated by Django 4.0.1 on 2022-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=64)),
                ('pinyin', models.CharField(max_length=64)),
                ('lang', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('audio', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('explanation', models.CharField(max_length=512)),
                ('char', models.CharField(max_length=512)),
                ('pinyin', models.CharField(max_length=512)),
                ('lang', models.CharField(max_length=512)),
                ('lit', models.CharField(max_length=512)),
                ('structure', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=64)),
                ('pinyin', models.CharField(max_length=64)),
                ('lang', models.CharField(max_length=64)),
                ('lit', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('audio', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
