# Generated by Django 4.0.2 on 2022-02-14 10:02

import django.core.validators
from django.db import migrations, models
import elements.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=elements.models.PathAndRename('audio/words/'), validators=[django.core.validators.FileExtensionValidator(['mp3', 'mp4', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=elements.models.PathAndRename('images/words/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=elements.models.PathAndRename('audio/video/'), validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
